config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'

  # Search routes
  get 'search', to: 'search#index'
  get 'search/all', to: 'search#show_all'

  # Other routes
  get 'movies/genre/:genre', to: 'movies#genre_movies', as: 'genre_movies'
  get 'tv_shows/genre/:genre', to: 'tv_shows#genre_tv_shows', as: 'genre_tv_shows'

  resources :movies, only: [:index, :show]
  resources :tv_shows, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie, optional: true
  belongs_to :tv_show, optional: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres

  has_many :tv_show_genres
  has_many :tv_shows, through: :tv_show_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watchlists
  has_many :favorites
  has_many :movie_genres
  has_many :genres, through: :movie_genres

  def video_url
    s3_client = Aws::S3::Client.new(region: ENV['REGION_CODE'])
    s3_client.presigned_url(:get_object, bucket: ENV['BUCKET_NAME'], key: self.video_key, expires_in: 3000)
  end

  def self.search(query)
    where('title ILIKE ?', "%#{query}")
  end
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :tv_show
  has_many :episodes
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  has_many :seasons
  has_many :watchlists
  has_many :favorites
  has_many :tv_show_genres
  has_many :genres, through: :tv_show_genres

  def video_url
    s3_client = Aws::S3::Client.new(region: ENV['REGION_CODE'])
    s3_client.presigned_url(:get_object, bucket: ENV['BUCKET_NAME'], key: self.video_key, expires_in: 3000)
  end

  def self.search(query)
    where('title ILIKE ?', "%#{query}")
  end
end

app/models/tv_show_genre.rb
class TvShowGenre < ApplicationRecord
  belongs_to :tv_show
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :movie, optional: true
  belongs_to :tv_show, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :current_user, :user_signed_in?

  def after_sign_out_path_for(resource_or_scope)
    new_user_registration_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @movies_by_genre = {}

    Genre.all.each do |genre|
      movies = @movies_by_genre[genre.name] = Movie.joins(:genres).where(genres: { name: genre.name }).limit(15)
      @movies_by_genre[genre.name] = movies
    end

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def genre_movies
    genre_name = params[:genre]
    @genre = Genre.find_by(name: genre_name)
    @movies = @genre ? @genre.movies : []
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @popular_movies = Movie.order(rating: :desc).limit(10);
    @popular_tv_shows = TvShow.order(rating: :desc).limit(10);
    @video_url = '/videos/anime.mp4';
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @movies = Movie.search(params[:query])
    @tv_shows = TvShow.search(params[:query])

    respond_to do |format|
      format.html
      format.json { render json: { movies: @movies, tv_shows: @tv_shows } }
    end
  end

  def show_all
    @movies = Movie.search(params[:query])
    @tv_shows = TvShow.search(params[:query])
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  def index
    @tv_shows = TvShow.all
    @tv_shows_by_genre = {}
    Genre.all.each do |genre|
      tv_shows = @tv_shows_by_genre[genre.name] = TvShow.joins(:genres).where(genres: { name: genre.name }).limit(15)
      @tv_shows_by_genre[genre.name] = tv_shows
    end
  end

  def show
    @tv_show = TvShow.find(params[:id])
  end

  def genre_tv_shows
    genre_name = params[:genre]
    @genre = Genre.find_by(name: genre_name)
    @tv_shows = @genre ? @genre.tv_shows : []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/movies/genre_movies.html.erb
<h1><%= @genre.name %> Movies</h1>
<% if @movies.any? %>
  <div class='movies-grid'>
    <% @movies.each do |movie| %>
      <div class='movie-genre'>
        <% if movie.poster_path %>
          <%= link_to movie_path(movie) do %>
            <%= image_tag "https://image.tmdb.org/t/p/w500#{movie.poster_path}" %>
          <% end %>
        <% end %>
        <div class='movie-genre-infos'>
          <h3><%= link_to movie.title, movie_path(movie) %></h3>
          <button class='index-play-btn'><i class="fa fa-play"></i> Play</button>
          <button class='index-icons-btn'><i class="fa fa-plus"></i></button>
          <p class='home-year'><%= movie.release_date.strftime("%Y") %></p>
          <p><%= movie.overview %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/movies/index.html.erb
<% @movies_by_genre.each_with_index do |(genre, movies), index| %>
  <% if movies.any? %>
    <h2>
      <%= genre %>
      <span class='more'>
        <%= link_to 'See more', genre_movies_path(genre: genre) %>
        <i class="fa fa-chevron-right"></i>
      </span>
    </h2>

    <%# Calculate z-index knowing that first container gets the highest z-index %>
    <% z_index = @movies_by_genre.size - index %>

    <div class="swiper-container" data-controller="swiper" data-slides-per-view="4" style="position: relative; z-index: <%= z_index %>;">
      <div class="swiper-wrapper">
        <% movies.each do |movie| %>
          <div class='swiper-slide'>
            <div class='movie-card' data-controller="poster">
              <% if movie.poster_path %>
                <%= link_to movie_path(movie) do %>
                    <%= image_tag "https://image.tmdb.org/t/p/w500#{movie.poster_path}", data: { poster_target: "image" } %>
                <% end %>
              <% end %>
              <div class='movie-card-infos'>
                <h3><%= link_to movie.title, movie_path(movie) %></h3>
                <button class='index-play-btn'><i class="fa fa-play"></i> Play</button>
                <button class='index-icons-btn'><i class="fa fa-plus"></i></button>
                <p class='home-year'><%= movie.release_date.strftime("%Y")%></p>
                <p><%= movie.overview %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
    </div>
  <% end %>
<% end %>

app/views/movies/show.html.erb
<div style="background: linear-gradient(to right, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.2)), url('https://image.tmdb.org/t/p/w500<%= @movie.poster_path %>');" class="ms-show-view">
  <div class='ms-content'>
    <h1><%= @movie.title %></h1>
    <p class='ms-overview'><%= @movie.overview %></p>

    <p class='ms-infos'>
      <span>IMDb <%= @movie.rating.round(1) %></span>
      <span><%= @movie.duration %> min</span>
      <span><%= @movie.release_date.strftime("%Y")%></span>
    </p>

    <p class='ms-genres'><%= @movie.category.gsub(',', ' • ') %></p>

    <div>
      <button class='play-btn'><i class="fa fa-play"></i> Play</button>
      <button class='icons-btn'><i class="fa fa-plus"></i></button>
      <button class='icons-btn'><i class="fa fa-heart"></i></button>
    </div>
  </div>
</div>

app/views/search/show_all.html.erb
<h2>Search Results for "<%= params[:query] %>"</h2>

<div>
  <h2>Movies</h2>
  <ul>
    <% @movies.each do |movie| %>
      <li><%= movie.title %></li>
    <% end %>
  </ul>

  <h2>TV Shows</h2>
  <ul>
    <% @tv_shows.each do |tv_show| %>
      <li><%= tv_show.title %></li>
    <% end %>
  </ul>
</div>

app/views/tv_shows/genre_tv_shows.html.erb
<h1><%= @genre.name %> TV Shows</h1>
<% if @tv_shows.any? %>
  <div class='movies-grid'>
    <% @tv_shows.each do |tv_show| %>
      <div class='movie-card'>
        <% if tv_show.poster_path %>
          <%= link_to tv_show_path(tv_show) do %>
            <%= image_tag "https://image.tmdb.org/t/p/w500#{tv_show.poster_path}" %>
          <% end %>
        <% end %>
        <h3><%= link_to tv_show.title, tv_show_path(tv_show) %></h3>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tv_shows/index.html.erb
<% @tv_shows_by_genre.each_with_index do |(genre, tv_shows), index| %>
  <% if tv_shows.any? %>
    <h2>
      <%= genre %>
      <span class='more'>
        <%= link_to 'See more', genre_tv_shows_path(genre: genre) %>
        <i class="fa fa-chevron-right"></i>
      </span>
    </h2>

    <%# Calculate z-index %>
    <% z_index = @tv_shows_by_genre.size - index %>

    <div class="swiper-container" data-controller="swiper" data-slides-per-view="6" style="position: relative; z-index: <%= z_index %>;">
      <div class="swiper-wrapper">
        <% tv_shows.each do |tv_show| %>
          <div class='swiper-slide'>
            <div class='movie-card'>
              <% if tv_show.poster_path %>
                <%= link_to tv_show_path(tv_show) do %>
                  <%= image_tag "https://image.tmdb.org/t/p/w500#{tv_show.poster_path}" %>
                <% end %>
              <% end %>
              <div class='movie-card-infos'>
                <h3><%= link_to tv_show.title, tv_show_path(tv_show) %></h3>
                <button class='index-play-btn'><i class="fa fa-play"></i> Play</button>
                <button class='index-icons-btn'><i class="fa fa-plus"></i></button>
                <% if tv_show.release_date? %>
                  <p class="home-year"><%= tv_show.release_date.strftime("%Y")%></p>
                <% end %>
                <p><%= tv_show.overview %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
    </div>
  <% end %>
<% end %>

app/views/tv_shows/show.html.erb
<div style="background: linear-gradient(to right, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.2)), url('https://image.tmdb.org/t/p/w500<%= @tv_show.poster_path %>');" class="ms-show-view">
  <div class='ms-content'>
    <h1><%= @tv_show.title %></h1>
    <p class='ms-overview'><%= @tv_show.overview %></p>

    <p class='ms-infos'>
      <span>IMDb <%= @tv_show.rating.round(1) %></span>
      <span><%= @tv_show.duration %> min</span>
      <span><%= @tv_show.release_date.strftime("%Y")%></span>
    </p>

    <p class='ms-genres'><%= @tv_show.category.gsub(',', ' • ') %></p>

    <div>
      <button class='play-btn'><i class="fa fa-play"></i> Play</button>
      <button class='icons-btn'><i class="fa fa-plus"></i></button>
      <button class='icons-btn'><i class="fa fa-heart"></i></button>
    </div>
  </div>
</div>