config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'

  # Search routes
  get 'search', to: 'search#index'
  get 'search/all', to: 'search#show_all'

  # Other routes
  get 'movies/genre/:genre', to: 'movies#genre_movies', as: 'genre_movies'
  get 'tv_shows/genre/:genre', to: 'tv_shows#genre_tv_shows', as: 'genre_tv_shows'

  resources :movies, only: [:index, :show]
  resources :tv_shows, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie, optional: true
  belongs_to :tv_show, optional: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres

  has_many :tv_show_genres
  has_many :tv_shows, through: :tv_show_genres
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watchlists
  has_many :favorites
  has_many :movie_genres
  has_many :genres, through: :movie_genres

  def video_url
    s3_client = Aws::S3::Client.new(region: ENV['REGION_CODE'])
    s3_client.presigned_url(:get_object, bucket: ENV['BUCKET_NAME'], key: self.video_key, expires_in: 3000)
  end

  def self.search(query)
    where('title ILIKE ?', "%#{query}")
  end
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :tv_show
  has_many :episodes
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  has_many :seasons
  has_many :watchlists
  has_many :favorites
  has_many :tv_show_genres
  has_many :genres, through: :tv_show_genres

  def video_url
    s3_client = Aws::S3::Client.new(region: ENV['REGION_CODE'])
    s3_client.presigned_url(:get_object, bucket: ENV['BUCKET_NAME'], key: self.video_key, expires_in: 3000)
  end

  def self.search(query)
    where('title ILIKE ?', "%#{query}")
  end
end

app/models/tv_show_genre.rb
class TvShowGenre < ApplicationRecord
  belongs_to :tv_show
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :movie, optional: true
  belongs_to :tv_show, optional: true
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @movies_by_genre = {}

    Genre.all.each do |genre|
      movies = @movies_by_genre[genre.name] = Movie.joins(:genres).where(genres: { name: genre.name }).limit(15)
      @movies_by_genre[genre.name] = movies
    end

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def genre_movies
    genre_name = params[:genre]
    @genre = Genre.find_by(name: genre_name)
    @movies = @genre ? @genre.movies : []
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @popular_movies = Movie.order(rating: :desc).limit(10);
    @popular_tv_shows = TvShow.order(rating: :desc).limit(10);
    @video_url = '/videos/anime.mp4';
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @movies = Movie.search(params[:query])
    @tv_shows = TvShow.search(params[:query])

    respond_to do |format|
      format.html
      format.json { render json: { movies: @movies, tv_shows: @tv_shows } }
    end
  end

  def show_all
    @movies = Movie.search(params[:query])
    @tv_shows = TvShow.search(params[:query])
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  def index
    @tv_shows = TvShow.all
    @tv_shows_by_genre = {}
    Genre.all.each do |genre|
      tv_shows = @tv_shows_by_genre[genre.name] = TvShow.joins(:genres).where(genres: { name: genre.name }).limit(15)
      @tv_shows_by_genre[genre.name] = tv_shows
    end
  end

  def show
    @tv_show = TvShow.find(params[:id])
  end

  def genre_tv_shows
    genre_name = params[:genre]
    @genre = Genre.find_by(name: genre_name)
    @tv_shows = @genre ? @genre.tv_shows : []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streamy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.3.0/color-thief.umd.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>

  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/navbar' %>
    <% else %>
      <%= render 'shared/navbar-unauth' %>
    <% end %>
    <div class="home-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <h2>Popular movies</h2>

  <div class="swiper-container" data-controller="swiper" data-slides-per-view="4" style="position: relative;z-index: 1;">
    <div class="swiper-wrapper">
      <% @popular_movies.each do |movie| %>
        <div class='swiper-slide' >
          <div class='home-movie-card'>
            <% if movie.poster_path %>
              <%= link_to movie_path(movie) do %>
                <%= image_tag "https://image.tmdb.org/t/p/w500#{movie.poster_path}" %>
              <% end %>
            <% end %>
            <div class='home-movie-card-infos'>
              <h4><%= link_to movie.title, movie_path(movie) %></h4>
              <button class='home-play-btn'><i class="fa fa-play"></i> Play</button>
              <button class='home-icons-btn'><i class="fa fa-plus"></i></button>
              <p class='home-year'><%= movie.release_date.strftime("%Y")%></p>
              <p><%= movie.overview %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>


  <h2>Popular tv shows</h2>

  <div class="swiper-container" data-controller="swiper" data-slides-per-view="4">
    <div class="swiper-wrapper">
      <% @popular_tv_shows.each do |show| %>
        <div class='swiper-slide'>
          <div class='home-movie-card'>
            <% if show.poster_path %>
              <%= link_to tv_show_path(show) do %>
                <%= image_tag "https://image.tmdb.org/t/p/w500#{show.poster_path}" %>
              <% end %>
            <% end %>
            <div class='movie-card-infos'>
              <h4><%= link_to show.title, tv_show_path(show) %></h4>
              <button class='home-play-btn'><i class="fa fa-play"></i> Play</button>
              <button class='home-icons-btn'><i class="fa fa-plus"></i></button>
              <p class="home-year"><%= show.release_date.strftime("%Y")%></p>
              <p><%= show.overview %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>

app/views/shared/_modal.html.erb
<div class="modal-overlay" data-modal-target="modalDiv" data-controller='search'>
  <div class="modal-content">
    <%= form_with url: search_path, method: :get, local: true do %>
      <%= text_field_tag :query, nil, placeholder: "Search", data: { action: "input->search#search", search_target: "input" } %>
    <% end %>
    <div id="search-results" data-search-target="results"></div>
  </div>
</div>

app/views/shared/_navbar-unauth.html.erb
<div class='navbar' data-controller="navbar" data-navbar-target="nav">
  <div class='navbar-logo-nav'>
    <%= image_tag 'streamy-clear.png', alt: 'Streamy logo', class: 'logo' %>
  </div>
  <div class="navbar-login-search">
    <div class="user-login-container">
      <%= image_tag 'user-test.png', alt: 'Unauth user logo', class: 'user-logo' %>
      <div class='nav-menu'>
        <p>YOUR ACCOUNT</p>
        <ul>
          <li><%= link_to 'Login', new_user_session_path, class: 'nav-btn-menu' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# Navbar laptop %>
<div class='navbar' data-controller="navbar" data-navbar-target="nav">
  <div class='navbar-logo-nav'>
    <%= link_to root_path do %>
      <%= image_tag 'streamy-clear.png', alt: 'Streamy logo', class: 'logo' %>
    <% end %>
    <%= link_to 'Home', root_path, class: "nav-btn #{'active' if current_page?(root_path)}" %>
    <%= link_to 'Movies', movies_path, class: "nav-btn #{'active' if current_page?(movies_path)}" %>
    <%= link_to 'TV Shows', tv_shows_path, class: "nav-btn #{'active' if current_page?(tv_shows_path)}" %>
  </div>
  <div class="navbar-login-search" data-controller="modal">
    <div class="navbar-icons">
      <i class="fa fa-magnifying-glass" data-modal-target="search"></i>
      <i class="fa fa-rectangle-list"></i>
      <i class='fa fa-bookmark nav-icon-book'></i>
      <%= render 'shared/modal' %>
    </div>
    <div class="user-login-container">
      <%= image_tag 'user-test.png', alt: 'User logo', class: 'user-logo', data: {navbar_target: 'navLogo'} %>
      <div class='nav-menu'>
        <p>YOUR ACCOUNT</p>
        <ul>
          <li><%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-btn-menu' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<%# Mobile/Tablets %>

<div class='mob-navbar' data-controller="navbar" data-navbar-target="nav">
  <div class="menu-container">
    <button class="mob-menu-btn">Menu <i class="fa fa-angle-down"></i></button>
    <div class="mob-nav-menu">
      <ul>
        <li><%= link_to 'Home', root_path, class: "nav-btn-menu #{'active' if current_page?(root_path)}" %></li>
        <li><%= link_to 'Movies', movies_path, class: "nav-btn-menu #{'active' if current_page?(movies_path)}" %></li>
        <li><%= link_to 'TV Shows', tv_shows_path, class: "nav-btn-menu #{'active' if current_page?(tv_shows_path)}" %></li>
        <li><%= link_to 'My Stuff', tv_shows_path, class: "nav-btn-menu #{'active' if current_page?(tv_shows_path)}" %></li>
      </ul>
    </div>
  </div>
  <div class='mob-navbar-logo-nav'>
    <%= link_to root_path do %>
      <%= image_tag 'streamy-clear.png', alt: 'Streamy logo', class: 'logo' %>
    <% end %>
  </div>
  <div class="mob-navbar-login-search">
    <div class="navbar-icons">
      <i class="fa fa-magnifying-glass"></i>
    </div>
    <div class="user-login-container">
      <%= image_tag 'user-test.png', alt: 'User logo', class: 'user-logo', data: {navbar_target: 'navLogo'} %>
      <div class='nav-menu'>
        <p>YOUR ACCOUNT</p>
        <ul>
          <li><%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-btn-menu' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>